/**
 * Topbar — the top chrome of the authenticated app.
 *
 * **F3 Part 1 (Task 4).** Sits above the page content,
 * pinned to the top. Houses the (mobile) menu toggle,
 * a breadcrumb slot, a search placeholder, a
 * notifications placeholder, and the user avatar.
 *
 * **Layout.** Three columns:
 *   - start — menu toggle (mobile) + breadcrumb
 *   - centre — global search
 *   - end   — notifications + user menu
 *
 * The breadcrumb is generated by the `BreadcrumbProvider`
 * (Task 6) — individual pages contribute metadata via
 * the `useBreadcrumb()` hook. The breadcrumb slot is
 * empty until a page registers its trail.
 *
 * **No business logic.** The search + notifications are
 * reusable placeholders; the actual search + notification
 * work lands in F4+ (Tasks 9 + 11+).
 *
 * **No routing.** The menu toggle calls back to the
 * parent layout; the breadcrumb items use the F1
 * `Breadcrumb` primitive which renders `<a href>`
 * (the call site can use `asChild` to swap in
 * `next/link`).
 */

"use client"

import { usePathname } from "next/navigation"
import type { ReactNode } from "react"

import { Breadcrumb, Icon, TooltipRoot, Topbar as TopbarPrimitive } from "@cortex/ui"

import { GlobalSearch } from "@/components/search/GlobalSearch"
import { useBreadcrumb } from "./BreadcrumbProvider"

export interface TopbarProps {
  /** Mobile drawer open handler. */
  onOpenMobileNav?: () => void
}

/** F4 placeholder — a bell + dot. The list itself lands later. */
function NotificationsButton() {
  return (
    <TooltipRoot content="Notifications (coming in F4)" side="bottom">
      <button
        type="button"
        aria-label="Notifications"
        className="relative flex h-9 w-9 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
      >
        <Icon name="Bell" className="h-4 w-4" />
        <span
          aria-hidden
          className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-ember-500"
        />
      </button>
    </TooltipRoot>
  )
}

/**
 * Build the breadcrumb trail for the current page.
 *
 * **Strategy.** The current URL pathname is the source
 * of truth for the *segments*. Each segment becomes a
 * `BreadcrumbItem` with a humanised label (capitalised,
 * dashes → spaces) and a link to the accumulated path.
 * The `BreadcrumbProvider` lets individual pages
 * override or annotate the auto-generated trail (e.g.
 * for "Documents" they can set a friendly label, or
 * for a "Document Details" page they can inject a
 * dynamic "Document Details" leaf).
 */
function useAutoBreadcrumb() {
  const pathname = usePathname() ?? "/"
  const override = useBreadcrumb()

  if (override && override.items.length > 0) return override.items

  // Always start with "Dashboard" (the home of the app).
  const segments = pathname.split("/").filter(Boolean)
  const items: { label: string; href?: string }[] = [
    { label: "Dashboard", href: "/app/dashboard" },
  ]

  // Walk the segments after `/app`. Skip "app" itself
  // (it's the route group marker). Stop *before* the
  // last segment so the leaf is the current page.
  const afterApp = segments.slice(segments.indexOf("app") + 1)
  if (afterApp.length === 0) return items

  let acc = "/app"
  for (let i = 0; i < afterApp.length - 1; i += 1) {
    acc += `/${afterApp[i]}`
    items.push({ label: humanise(afterApp[i] ?? ""), href: acc })
  }
  // Leaf (current page) — no href so it renders as
  // "current page" (bold + non-link) in the F1 Breadcrumb.
  items.push({ label: humanise(afterApp[afterApp.length - 1] ?? "") })
  return items
}

function humanise(segment: string): string {
  return segment
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ")
}

export function Topbar({ onOpenMobileNav }: TopbarProps): ReactNode {
  const items = useAutoBreadcrumb()

  return (
    <TopbarPrimitive
      start={
        <>
          {onOpenMobileNav ? (
            <TooltipRoot content="Open navigation" side="bottom">
              <button
                type="button"
                onClick={onOpenMobileNav}
                aria-label="Open navigation"
                className="flex h-9 w-9 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 md:hidden"
              >
                <Icon name="Menu" className="h-4 w-4" />
              </button>
            </TooltipRoot>
          ) : null}
          <Breadcrumb items={items} className="hidden sm:flex" />
        </>
      }
      center={<GlobalSearch />}
      end={
        <>
          <NotificationsButton />
          {/* UserMenu lives in the end slot; it's imported
              by the parent layout to keep this file
              single-purpose. See the layout for the wire. */}
        </>
      }
    />
  )
}
