/**
 * OpenAPI codegen — fetches the backend's `/openapi.json` and
 * writes `src/types.ts` with the strict, fully-typed schema.
 *
 * The runtime (`src/runtime.ts`) consumes the generated schema
 * and turns it into a typed `ApiClient` for app code.
 *
 * Usage:
 *   pnpm --filter @cortex/api-client generate
 *
 * Or from the workspace root:
 *   pnpm codegen
 *
 * The script reads `NEXT_PUBLIC_API_URL` from the environment
 * (default `http://localhost:8000`).
 */

import { mkdir, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import openapiTS, { astToString } from "openapi-typescript"

const __dirname = dirname(fileURLToPath(import.meta.url))
const TYPES_PATH = resolve(__dirname, "../src/types.ts")
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"

async function main() {
  const specUrl = `${API_URL.replace(/\/$/, "")}/openapi.json`
  process.stdout.write(`[api-client] fetching ${specUrl} ...\n`)

  // openapi-typescript fetches the URL itself, so we don't need to
  // download the body first. A HEAD-style probe keeps the error
  // message friendly if the backend isn't running.
  const probe = await fetch(specUrl, { method: "HEAD" }).catch(() => null)
  if (probe && !probe.ok) {
    throw new Error(
      `Failed to fetch OpenAPI spec from ${specUrl}: ${probe.status} ${probe.statusText}. Is the backend running?`,
    )
  }

  process.stdout.write("[api-client] generating TypeScript schema ...\n")
  const ast = await openapiTS(new URL(specUrl))
  const types = astToString(ast)

  const banner = `/**\n * AUTO-GENERATED by scripts/generate.ts — do not edit by hand.\n * Source: ${specUrl}\n * Regenerate with: pnpm --filter @cortex/api-client generate\n */\n\n`
  const body = banner + types

  await mkdir(dirname(TYPES_PATH), { recursive: true })
  await writeFile(TYPES_PATH, body, "utf-8")
  process.stdout.write(`[api-client] wrote ${TYPES_PATH}\n`)
}

main().catch((err) => {
  console.error("[api-client] codegen failed:", err)
  process.exit(1)
})
