"""
Metrics compatibility shim (V3 → V4).

V3 had a tiny ``metrics.py`` that exposed two counters and
called them via the Prometheus client. V4 replaces the
contents of that module with a fully-namespaced registry of
counters / histograms / gauges in
:mod:`src.observability.infrastructure.metrics`.

This shim re-exports the new module's public surface so any
existing V3 import keeps working without a code change.
"""

from src.observability.infrastructure.metrics import (
    EMBEDDING_CACHE_HITS_TOTAL,
    EMBEDDING_CACHE_MISSES_TOTAL,
    EMBEDDING_CALLS_TOTAL,
    EMBEDDING_DURATION_SECONDS,
    EMBEDDING_TOKENS_TOTAL,
    EMBEDDING_VECTORS_TOTAL,
    HTTP_REQUESTS_IN_FLIGHT,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_TOTAL,
    LLM_CALLS_TOTAL,
    LLM_COST_TOTAL,
    LLM_INPUT_TOKENS_TOTAL,
    LLM_LATENCY_SECONDS,
    LLM_OUTPUT_TOKENS_TOTAL,
    REDIS_CACHE_HITS_TOTAL,
    REDIS_CACHE_MISSES_TOTAL,
    GRAPH_LLM_EXTRACTION_TOKENS_TOTAL,
    GRAPH_QUERIES_TOTAL,
    GRAPH_RETRIEVAL_DURATION_SECONDS,
    GRAPH_TRAVERSAL_DURATION_SECONDS,
    KG_ENTITIES_EXTRACTED_TOTAL,
    KG_EXTRACTION_FAILURES_TOTAL,
    KG_PIPELINE_RUNS_TOTAL,
    KG_RELATIONSHIPS_EXTRACTED_TOTAL,
    REGISTRY,
    RERANK_CALLS_TOTAL,
    RERANK_CANDIDATES_TOTAL,
    RERANK_DURATION_SECONDS,
    RETRIEVAL_DURATION_SECONDS,
    RETRIEVAL_REQUESTS_TOTAL,
    RETRIEVAL_RESULTS_COUNT,
    USAGE_RECORDING_FAILURES_TOTAL,
    WORKER_TASK_DURATION_SECONDS,
    WORKER_TASK_FAILURES_TOTAL,
    WORKER_TASK_RETRIES_TOTAL,
    WORKER_TASKS_TOTAL,
    render_latest,
)


__all__ = [
    "EMBEDDING_CACHE_HITS_TOTAL",
    "EMBEDDING_CACHE_MISSES_TOTAL",
    "EMBEDDING_CALLS_TOTAL",
    "EMBEDDING_DURATION_SECONDS",
    "EMBEDDING_TOKENS_TOTAL",
    "EMBEDDING_VECTORS_TOTAL",
    "HTTP_REQUESTS_IN_FLIGHT",
    "HTTP_REQUEST_DURATION_SECONDS",
    "HTTP_REQUESTS_TOTAL",
    "LLM_CALLS_TOTAL",
    "LLM_COST_TOTAL",
    "LLM_INPUT_TOKENS_TOTAL",
    "LLM_LATENCY_SECONDS",
    "LLM_OUTPUT_TOKENS_TOTAL",
    "REDIS_CACHE_HITS_TOTAL",
    "REDIS_CACHE_MISSES_TOTAL",
    "GRAPH_LLM_EXTRACTION_TOKENS_TOTAL",
    "GRAPH_QUERIES_TOTAL",
    "GRAPH_RETRIEVAL_DURATION_SECONDS",
    "GRAPH_TRAVERSAL_DURATION_SECONDS",
    "KG_ENTITIES_EXTRACTED_TOTAL",
    "KG_EXTRACTION_FAILURES_TOTAL",
    "KG_PIPELINE_RUNS_TOTAL",
    "KG_RELATIONSHIPS_EXTRACTED_TOTAL",
    "REGISTRY",
    "RERANK_CALLS_TOTAL",
    "RERANK_CANDIDATES_TOTAL",
    "RERANK_DURATION_SECONDS",
    "RETRIEVAL_DURATION_SECONDS",
    "RETRIEVAL_REQUESTS_TOTAL",
    "RETRIEVAL_RESULTS_COUNT",
    "USAGE_RECORDING_FAILURES_TOTAL",
    "WORKER_TASK_DURATION_SECONDS",
    "WORKER_TASK_FAILURES_TOTAL",
    "WORKER_TASK_RETRIES_TOTAL",
    "WORKER_TASKS_TOTAL",
    "render_latest",
]

